[Service]
Nice=15
IOSchedulingClass=idle
CPUAccounting=true
CPUWeight=10
CPUQuota=20%
IOAccounting=true
IOWeight=10
IOReadBandwidthMax=/dev/vda 1M
IOWriteBandwidthMax=/dev/vda 512K
IOReadIOPSMax=/dev/vda 20
IOWriteIOPSMax=/dev/vda 20
MemoryAccounting=true
MemoryHigh=48M
MemoryMax=80M
OOMPolicy=continue
TasksMax=32
TimeoutStopSec=30s
